### **Assignment: Introduction to Linear Algebra and NumPy**

#### **Objective:**
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.


### **Working with NumPy**

NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

**Task 1:** 
- Import the `numpy` library and check its version.


In [1]:
import numpy as np
print(np.__version__)

2.3.1



### **Creating a NumPy Array:**

NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

**Task 2:**
- Create a 1D NumPy array from a Python list of numbers: `[1, 2, 3, 4, 5]`.
- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
- Generate an array of 10 evenly spaced values between 0 and 5.

In [ ]:
lst=[1,2,3,4,5]
arr1=np.array(lst)
arr1
#2-D array of shape 3*3
arr2=np.random.randint(low=1,high=9,size=(3,3))
arr2


array([[2, 4, 4],
       [6, 4, 2],
       [2, 8, 7]], dtype=int32)

In [6]:
#evenly spaced array
np.linspace(start=0,stop=5,num=10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### **Indexing and Slicing Arrays:**

Indexing and slicing allow you to access and modify specific elements of an array.

**Task 3:**
- Access the element in the second row, third column of the 2D array you created above.
- Slice the first two rows and the first two columns from the same array.
- Modify the value in the last row and first column to 100.


In [7]:
arr2[1][2]

np.int32(2)

In [9]:
sliced=arr2[:2,:2]
print(sliced)

[[2 4]
 [6 4]]


In [10]:
arr2[2,0]=100
print(arr2)

[[  2   4   4]
 [  6   4   2]
 [100   8   7]]


### **Properties and Methods of NumPy Arrays**

NumPy arrays have several useful properties and methods.

**Task 4:**
- Find the shape, size, and data type of the 2D array.
- Change the 1D array into a 2D array of shape (5,1).
- Flatten a multi-dimensional array back into a 1D array.

In [11]:
#finding shape,size,and data type of 2-D array
print(arr2)
print(f"\nshape:{arr2.shape}")
print(f"Size:{arr2.size}")
print(f"datatype:{arr2.dtype}")

[[  2   4   4]
 [  6   4   2]
 [100   8   7]]

shape:(3, 3)
Size:9
datatype:int32


In [13]:
#1-D array into 2-D 
arr1=np.random.randint(1,10,size=5)
print(f"Array:{arr1}")
reshaped=arr1.reshape(5,1)
print(f"2-D array:{reshaped}\n")
print(f"Shape of array:{reshaped.shape}")


Array:[9 6 8 6 2]
2-D array:[[9]
 [6]
 [8]
 [6]
 [2]]

Shape of array:(5, 1)


In [17]:
#flattening array
arr3=np.random.randint(low=0,high=50,size=(3,3,3))
print(f"Multidimensional array:{arr3}\n")
flatten_array=arr3.flatten()
print(f"\nFlattened array:{flatten_array}")

Multidimensional array:[[[ 0 18 14]
  [35 34 34]
  [45 28 27]]

 [[46 29 47]
  [18 11  3]
  [43 14  1]]

 [[47 23 17]
  [ 9 47 28]
  [44 35  9]]]


Flattened array:[ 0 18 14 35 34 34 45 28 27 46 29 47 18 11  3 43 14  1 47 23 17  9 47 28
 44 35  9]


### **Operations on NumPy Arrays**

Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

**Task 5:**
- Add 5 to every element in the 1D array.
- Multiply the 2D array by 3.
- Perform matrix multiplication between the following two arrays:  
    ```python
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

In [22]:

print(arr1)
print(f"Adding 5 to array:{arr1+5}\n")
print(arr2)
print(f"\nMultiplying by 3 to array2:{arr2*3}")

[9 6 8 6 2]
Adding 5 to array:[14 11 13 11  7]

[[  2   4   4]
 [  6   4   2]
 [100   8   7]]

Multiplying by 3 to array2:[[  6  12  12]
 [ 18  12   6]
 [300  24  21]]


In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
arr_mult=np.dot(A,B)
print(f"Product:{arr_mult}")

Product:[[19 22]
 [43 50]]


### **Understanding Broadcasting**

Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

**Task 6:**
- Create a 3x3 matrix of ones and a 1D array of length 3.
- Add the 1D array to each row of the matrix using broadcasting.

In [28]:
arr_ones=np.ones(shape=(3,3))
print(f"Ones array:{arr_ones}")
arr4=np.array([5,6,7])
print(f"1-D array:{arr4}")
arr_sum=arr4+arr_ones
print(f"Sum:{arr_sum}")

Ones array:[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1-D array:[5 6 7]
Sum:[[6. 7. 8.]
 [6. 7. 8.]
 [6. 7. 8.]]
